datamart:
  project_dir: "datamart"
  main_class: "itmo.lab7.Main"
  local_config: "conf/datamart-local.conf"
  docker_config: "conf/datamart-docker.conf"

model:
  app_config: "configs/app_config.yaml"
  spark_config: "configs/spark_config.yaml"

bootstrap:
  enabled_by_default: true
  source_file: "data/raw/openfoodfacts_sample.jsonl"
  source_lines: 15000
