mongodb {
  uri = "mongodb://mongodb:27017"
  database = "itmo_bigdata"
  sourceCollection = "openfoodfacts_source"
  martCollection = "openfoodfacts_mart_features"
  resultsCollection = "kmeans_results"
  runsCollection = "mart_runs"
}

paths {
  preparedParquet = "/app/data/processed/openfoodfacts_features.parquet"
  modelPredictionsParquet = "/app/data/output/openfoodfacts_clusters.parquet"
  modelMetricsJson = "/app/data/output/cluster_metrics.json"
}

preprocessing {
  energyMin = 0.0
  energyMax = 1200.0
  fatMin = 0.0
  fatMax = 100.0
  carbohydratesMin = 0.0
  carbohydratesMax = 100.0
  sugarsMin = 0.0
  sugarsMax = 100.0
  proteinsMin = 0.0
  proteinsMax = 100.0
  saltMin = 0.0
  saltMax = 100.0
}

spark {
  master = "spark://spark-master:7077"
  appName = "Lab7DataMartK8s"
  shufflePartitions = 8
}
