apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app.kubernetes.io/name: {{ include "lab8-migration.name" . }}
    app.kubernetes.io/component: spark-worker
spec:
  replicas: {{ .Values.spark.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: spark-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/component: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: bitnami/spark:4.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: SPARK_MODE
              value: worker
            - name: SPARK_MASTER_URL
              value: spark://spark-master:7077
            - name: SPARK_WORKER_MEMORY
              value: "1024m"
            - name: SPARK_WORKER_CORES
              value: "1"
            - name: SPARK_WORKER_WEBUI_PORT
              value: "8081"
          ports:
            - containerPort: 8081
              name: webui
          resources:
{{ toYaml .Values.spark.worker.resources | indent 12 }}
