apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app.kubernetes.io/name: {{ include "lab8-migration.name" . }}
    app.kubernetes.io/component: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: spark-master
  template:
    metadata:
      labels:
        app.kubernetes.io/component: spark-master
    spec:
      containers:
        - name: spark-master
          image: bitnami/spark:4.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: SPARK_MODE
              value: master
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
          ports:
            - containerPort: 7077
              name: spark
            - containerPort: 8080
              name: webui
          resources:
{{ toYaml .Values.spark.master.resources | indent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    app.kubernetes.io/name: {{ include "lab8-migration.name" . }}
    app.kubernetes.io/component: spark-master
spec:
  type: {{ .Values.spark.master.serviceType }}
  selector:
    app.kubernetes.io/component: spark-master
  ports:
    - name: spark
      port: 7077
      targetPort: spark
    - name: webui
      port: 8080
      targetPort: webui
